version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb_batman"
    ports:
      - 27017:27017
    command: --smallfiles
  app:
    image: batman/cart
    ports:
      - 8080:8080
    links:
      - mongodb