version: "3"
services:
  mongodb:
    image: mongo:3.2.4
    container_name: "mongodb_batman"
    ports:
      - 27017:27017
    command: --smallfiles
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: "jaeger"
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
  app:
    image: batman/cart
    ports:
      - 9091:9091
    links:
      - mongodb