spring:
  application:
    name: microservice-cart
  data:
    mongodb:
      uri: mongodb://mongodb_batman/cart_batman
      database: cart_batman
      host: localhost
      port: 27017
  datasource:
    driverClassName: MongoDB
  kafka:
    producer:
      bootstrap-servers: 18.210.232.248:9092,52.202.175.72:9092,18.204.118.23:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 18.210.232.248:9092,52.202.175.72:9092,18.204.118.23:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  client:
  maxAttempts: 3
  backoff: 2000

server:
  port: 9091

logging:
  level:
    .: error
    org:
      springframework.data: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      port: 5775