spring:
  application:
    name: microservice-cart
  data:
    mongodb:
      uri: mongodb://mongodb_batman/cart_batman
      #uri: mongodb://localhost/cart_batman
      database: cart_batman
      host: localhost
      port: 27017
  datasource:
    driverClassName: MongoDB
  kafka:
    producer:
      bootstrap-servers: 172.31.17.129:9092
      #bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 172.31.17.129:9092
      #bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

hackathon:
  product:
    url: https://0e3hqxxh35.execute-api.us-east-1.amazonaws.com/v1
  external:
    url: https://0e3hqxxh35.execute-api.us-east-1.amazonaws.com/v1
  analytics:
    url: https://0e3hqxxh35.execute-api.us-east-1.amazonaws.com/v1


server:
  port: 9091

logging:
  level:
    .: error
    org:
      springframework.data: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    metrics:
      enabled: false
    prometheus:
      enabled: true

opentracing:
  jaeger:
    udp-sender:
      host: jaeger
      #host: localhost
      port: 5775